### ISSUE TITLE
AutoLoginGuard cannot be used as a canLoad guard?

### ISSUE THREAD

**Issue by ColinLaws** [damienbod/angular-auth-oidc-client#1025]
Following the example here, I tried implementing the AutoLoginGuard in the `canLoad` of one of my routes. 
https://github.com/damienbod/angular-auth-oidc-client/blob/bf2dfd5f7253b8fc7ef29060de043fcb9b46b995/projects/sample-code-flow-auto-login/src/app/app.routes.ts#L16

The following error is thrown to the console:
```
core.js:6157 ERROR Error: Uncaught (in promise): Error: Invalid CanLoad guard
Error: Invalid CanLoad guard
    at vendor.js:135257:23 [angular]
    at Array.map (<anonymous>) [angular]
    at ApplyRedirects.runCanLoadGuards (router.js:2787) [angular]
    at ApplyRedirects.getChildConfig (router.js:2769) [angular]
    at ApplyRedirects.matchSegmentAgainstRoute (router.js:2740) [angular]
    at ApplyRedirects.expandSegmentAgainstRoute (router.js:2689) [angular]
    at MergeMapSubscriber.project (router.js:2667) [angular]
    at MergeMapSubscriber._tryNext (mergeMap.js:44) [angular]
    at MergeMapSubscriber._next (mergeMap.js:34) [angular]
    at MergeMapSubscriber.next (Subscriber.js:49) [angular]
    at Observable._subscribe (subscribeToArray.js:3) [angular]
    at Observable._trySubscribe (Observable.js:42) [angular]
    at Observable.subscribe (Observable.js:28) [angular]
    at MergeMapOperator.call (mergeMap.js:19) [angular]
    at resolvePromise (zone-evergreen.js:798) [angular]
    at resolvePromise (zone-evergreen.js:750) [angular]
    at polyfills.js:10144:21 [angular]
    at Object.onInvokeTask (core.js:28522) [angular]
    at drainMicroTaskQueue (zone-evergreen.js:569) [<root>]
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484) [<root>]
    at invokeTask (zone-evergreen.js:1621) [<root>]
    at HTMLAnchorElement.globalZoneAwareCallback (zone-evergreen.js:1647) [<root>]
```

**Comment by ColinLaws** [comment]
Closed, as this was a duplicate of #1022
