### ISSUE TITLE
ng add angular-auth-oidc-client does not work with yarn as package manager

### ISSUE THREAD

**Issue by Lonli-Lokli** [damienbod/angular-auth-oidc-client#1080]
**Describe the bug**
ng add angular-auth-oidc-client does not work with yarn as package manager

**To Reproduce**
Create angular project with yarn as PM
run ng add angular-auth-oidc-client
**Expected behavior**
no errors

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
logs:
[error] Error: Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] ...
  1. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] ...

While running add angular-auth-oidc-client@11.2.0 --silent
Package install failed, see above.
    at Object.installPackage (/Users/lonli-lokli/cv-app/frontend/cv-ui/node_modules/@angular/cli/tasks/install-package.js:40:15)
    at AddCommand.run (/Users/lonli-lokli/cv-app/frontend/cv-ui/node_modules/@angular/cli/commands/add-impl.js:149:31)
    at async AddCommand.validateAndRun (/Users/lonli-lokli/cv-app/frontend/cv-ui/node_modules/@angular/cli/models/command.js:134:28)
    at async Object.runCommand (/Users/lonli-lokli/cv-app/frontend/cv-ui/node_modules/@angular/cli/models/command-runner.js:198:24)
    at async default_1 (/Users/lonli-lokli/cv-app/frontend/cv-ui/node_modules/@angular/cli/lib/cli/index.js:59:31)

**Comment by damienbod** [comment]
Hi @Lonli-Lokli  I tested this with yarn (on windows) and it works fine. I don't have a MAC to test but I don't think this should be different. We use npm to build and develop the lib. 

This is what I did and worked:

```
yarn install

yarn run build-lib

yarn start
```

Greetings Damien

**Comment by damienbod** [comment]
closing this as I don't see a way of fixing this.

Sorry and thanks for reporting this.

Greetings Damien
