### ISSUE TITLE
ERROR ReferenceError: 'URLSearchParams' is undefined in IE and Edge

### ISSUE THREAD

**Issue by rpipkin** [damienbod/angular-auth-oidc-client#113]
Guys, I love the direction of this project.  I was using your raw ts files from before it was an npm package.  I recently replace those with this npm package version.  In IE and Edge, issuing a login request creates this bug in the console and never goes to the Identity server login page.  Here's the error with the stack:

ERROR ReferenceError: 'URLSearchParams' is undefined
"ReferenceError: 'URLSearchParams' is undefined
   at OidcSecurityService.prototype.createAuthorizeUrl (http://localhost:5003/dist/app.bundle.js:27407:9)
   at OidcSecurityService.prototype.authorize (http://localhost:5003/dist/app.bundle.js:27127:9)
   at AppComponent.prototype.login (http://localhost:5003/dist/app.bundle.js:82679:9)
   at Anonymous function (Function code:10:11)
   at handleEvent (http://localhost:5003/dist/app.bundle.js:12205:87)
   at callWithDebugContext (http://localhost:5003/dist/app.bundle.js:13666:9)
   at debugHandleEvent (http://localhost:5003/dist/app.bundle.js:13254:5)
   at dispatchEvent (http://localhost:5003/dist/app.bundle.js:8809:5)
   at Anonymous function (http://localhost:5003/dist/app.bundle.js:9420:13)
   at Anonymous function (http://localhost:5003/dist/app.bundle.js:39761:9)"

There is a conversation in Angular's github discussing how URLSearchParams is a global variable and can easily be confused with the Angular class. https://github.com/angular/angular/issues/16378
I have a sneaking suspicion that IE and Edge are finding the wrong object to load.  If I get time I'll try to clone and fix and submit a Pull Request, but if you guys get to it first, it would be hugely appreciated.

**Comment by robisim74** [comment]
@rpipkin thanks for reporting. This is a bug.

@damienbod The error was created by this commit: https://github.com/damienbod/angular-auth-oidc-client/commit/d0745e7a828dd7e319e848acbdeabe83419d998c, when you moved to HttpClient: first `URLSearchParams` was imported from `Http` module, while the local variable is now being used.

**Comment by robisim74** [comment]
Has pr: #114

**Comment by damienbod** [comment]
fixed in 3.0.2, thanks @rpipkin @robisim74

**Comment by mcano808** [comment]
A question- how can I make sure I get this fix into my current angular app?

**Comment by damienbod** [comment]
@mcano808 you can use the npm

https://www.npmjs.com/package/angular-auth-oidc-client

Greetings Damien
