### ISSUE TITLE
fix TSLint errors

### ISSUE THREAD

**Issue by MovGP0** [damienbod/angular-auth-oidc-client#117]
remove those unused imports: 
```
Error at src\services\auth.well-known-endpoints.ts:4:10: 'Observer' is declared but its value is never read.
Error at src\services\auth.well-known-endpoints.ts:5:10: 'BehaviorSubject' is declared but its value is never read.
Error at src\services\oidc.security.check-session.ts:4:10: 'BehaviorSubject' is declared but its value is never read.
Error at src\services\oidc.security.check-session.ts:66:13: 'subscription' is declared but its value is never read.
Error at src\services\oidc.security.service.ts:2:22: 'HttpHeaders' is declared but its value is never read.
Error at src\services\oidc.security.service.ts:3:29: 'isPlatformServer' is declared but its value is never read.
Error at src\services\oidc.security.service.ts:235:29: 'headerDecoded' is declared but its value is never read.
Error at src\services\oidc.security.service.ts:537:13: 'runGetSigningKeys' is declared but its value is never read.
Error at src\services\oidc.security.service.ts:573:13: 'subscription' is declared but its value is never read.
Error at src\services\oidc.security.user-service.ts:4:10: 'Observer' is declared but its value is never read.
Error at src\services\oidc.security.user-service.ts:5:10: 'BehaviorSubject' is declared but its value is never read.
Error at src\services\oidc.security.user-service.ts:21:17: Property 'authConfiguration' is declared but its value is never read.
Error at tests\services\oidc.security.service.spec.ts:4:10: 'NgModule' is declared but its value is never read.
Error at tests\services\oidc.security.service.spec.ts:8:10: 'HttpClient' is declared but its value is never read.
Error at tests\services\oidc.security.service.spec.ts:8:22: 'HttpHeaders' is declared but its value is never read.
```

**Comment by MovGP0** [comment]
`oidc.security.service.spec.ts` is missing the following imports: 
```
import { beforeEach, expect, describe, it } from 'karma';
```

**Comment by MovGP0** [comment]
expects are used in reverse. instead of `expect(expectValue).toEqual(value);` it should read `expect(value).toEqual(expectValue);`.

**Comment by damienbod** [comment]
Hi @MovGP0 

The tests are run:

https://travis-ci.org/damienbod/angular-auth-oidc-client/builds/293584182?utm_source=github_status&utm_medium=notification

I don't have these tslint messages. I'll check again

Greetings Damien

**Comment by MovGP0** [comment]
I was using a newer version of the TS compiler

**Comment by damienbod** [comment]
fixed using latest typescript
