### ISSUE TITLE
[Bug]: Crash on page load if cookies and site data are disabled

### ISSUE THREAD

**Issue by LGLN-LS** [damienbod/angular-auth-oidc-client#1660]
### Version

14.1.5

### Please provide the exception or error you saw

```true
DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at DefaultSessionStorageService.read (http://localhost:4200/vendor.js:119650:5)
    at BrowserStorageService.read (http://localhost:4200/vendor.js:112629:55)
    at StoragePersistenceService.read (http://localhost:4200/vendor.js:112717:53)
    at ConfigurationService.enhanceConfigWithWellKnownEndpoint (http://localhost:4200/vendor.js:117806:82)
    at ConfigurationService.handleConfig (http://localhost:4200/vendor.js:117800:42)
    at http://localhost:4200/vendor.js:117776:59
    at Array.map (<anonymous>)
    at ConfigurationService.prepareAndSaveConfigs (http://localhost:4200/vendor.js:117776:45)
    at http://localhost:4200/vendor.js:117736:114
    at doInnerSub (http://localhost:4200/vendor.js:10974:70)
```
```


### Steps to reproduce the behavior

```true
If a user has disabled "Cookies and Site Data" in the browser settings, the above crash immediately occurs when loading the page.

To disable cookies and site data follow this instructions:
- Edge: https://cookie-script.com/knowledge-base/disable-cookies-edge
- Firefox: https://cookie-script.com/knowledge-base/disable-cookies-firefox
- Chrome: https://cookie-script.com/knowledge-base/disable-cookies-chrome
```

### A clear and concise description of what you expected to happen.

```true
I expect no crash on page load. The user should be logged out. Login should not work, maybe throw an exception when calling the authorize() method.
```

**Comment by damienbod** [comment]
The lib does not use cookies or same site features. If this happens, it's the settings on the OIDC server.

**Comment by damienbod** [comment]
ah, ok the app uses session storage per default. If you disable this it will not work and you would need to implement some type of custom storage. Question is, why would you disable session storage? 

We could add docs for this, good?

Greetings Damien
