### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lufo88ita** [damienbod/angular-auth-oidc-client#1667]
### Version

15.0.3

### Please provide the exception or error you saw

```true
"app.component.ts:19 TypeError: Cannot read properties of undefined (reading 'xhrFactory')
    at Observable._subscribe (http.mjs:1742:30)
    at Observable._trySubscribe (Observable.js:37:25)
    at Observable.js:31:30
    at errorContext (errorContext.js:19:9)
    at Observable.subscribe (Observable.js:22:21)
    at doInnerSub (mergeInternals.js:19:44)
    at outerNext (mergeInternals.js:14:57)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at Observable._subscribe (innerFrom.js:51:24)"
```

### Steps to reproduce the behavior

```true
Install and configure the library to use code flow and use the method checkAuthIncludingServer to try to login.
```

### A clear and concise description of what you expected to happen.

```true
No errors in the console
```

### Additional context

I double check the problem is related to this library. I upgrade just this package from 15.0.2 to 15.0.3 and the error, that I reported above. appear.

I use Angular 14 and ngrxstore. These are the packages I installed:

```
"dependencies": {
    "@angular/animations": "^14.2.12",
    "@angular/cdk": "^14.2.7",
    "@angular/common": "^14.2.12",
    "@angular/compiler": "^14.2.12",
    "@angular/core": "^14.2.12",
    "@angular/forms": "^14.2.12",
    "@angular/google-maps": "^14.2.7",
    "@angular/platform-browser": "^14.2.12",
    "@angular/platform-browser-dynamic": "^14.2.12",
    "@angular/platform-server": "^14.2.12",
    "@angular/router": "^14.2.12",
    "@biesbjerg/ngx-translate-extract-marker": "^1.0.0",
    "@microsoft/signalr": "^6.0.13",
    "@ngneat/cashew": "^3.0.0",
    "@ngrx/component": "^14.3.3",
    "@ngrx/effects": "^14.3.3",
    "@ngrx/router-store": "^14.3.3",
    "@ngrx/store": "^14.3.3",
    "@ngrx/store-devtools": "^14.3.3",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@popperjs/core": "^2.11.6",
    "@sentry/angular": "^7.34.0",
    "@stripe/stripe-js": "^1.46.0",
    "angular-auth-oidc-client": "15.0.2",
    "bulma": "^0.9.3",
    "bulma-extensions": "^6.2.7",
    "countries-list": "^2.6.1",
    "guid-typescript": "~1.0.9",
    "ibantools": "^4.2.2",
    "jdenticon": "^3.2.0",
    "json5": "^2.2.3",
    "jsvat": "^2.5.3",
    "lodash-es": "^4.17.21",
    "ng-recaptcha": "^10.0.0",
    "ngx-iban": "^14.0.0",
    "ngx-jdenticon": "^1.0.4",
    "ngx-permissions": "^14.0.0",
    "ngx-pipes": "^3.2.0",
    "ngx-popperjs": "^14.1.6",
    "ngx-scrollbar": "^10.0.1",
    "ngx-stripe": "^14.3.2",
    "primeicons": "^6.0.1",
    "primeng": "^14.2.3",
    "run-script-os": "^1.1.6",
    "rxjs": "~7.5.7",
    "tslib": "^2.5.0",
    "world_countries_lists": "^2.6.0",
    "zone.js": "~0.11.8"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.10",
    "@angular/cli": "^14.2.10",
    "@angular/compiler-cli": "^14.2.12",
    "@bartholomej/ngx-translate-extract": "^8.0.2",
    "@creativebulma/bulma-badge": "^1.0.1",
    "@creativebulma/bulma-divider": "^1.1.0",
    "@types/jasmine": "~4.0.3",
    "@types/jasminewd2": "~2.0.10",
    "@types/lodash-es": "^4.17.6",
    "@types/node": "^17.0.45",
    "jasmine-core": "~4.1.1",
    "karma": "~6.3.20",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.0.1",
    "karma-jasmine-html-reporter": "^1.7.0",
    "typescript": "~4.8.4"
  }
```

**Comment by FabianGosebrink** [comment]
Can you create a new repository with only the bare minimum to reproduce the error? Thanks.

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.

**Comment by fritzwf** [comment]
Not sure if you should be using version 15 when your angular is 14.

**Comment by lufo88ita** [comment]
You're right. I will try to upgrade angular.
