### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ismaeli34** [damienbod/angular-auth-oidc-client#1734]
### Version

"angular-auth-oidc-client": "15.0.4",

### Please provide the exception or error you saw

```true
ROR Error: TypeError: Cannot read properties of undefined (reading 'xhrFactory')
  at angular-auth-oidc-client.mjs:3439:37
    at Observable.init [as _subscribe] (throwError.js:5:51)
    at Observable._trySubscribe (Observable.js:37:25)
    at Observable.js:31:30
    at errorContext (errorContext.js:19:9)
    at Observable.subscribe (Observable.js:22:21)
    at catchError.js:23:27
    at SafeSubscriber.<anonymous> (lift.js:10:28)
    at Observable.js:26:30
    at errorContext (errorContext.js:19:9)
h
```

### A clear and concise description of what you expected to happen.

```true
I have implemented angular auth oidc in my project but when I click on Login button. I get this error. I do not know why ? Could you please help me to resolve this issue.
```

**Comment by damienbod** [comment]
hi @ismaeli34 Can you compare your solution to the samples?

https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-refresh-tokens/src

Greetings Damien

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
