### ISSUE TITLE
Error 'RangeError: Maximum call stack size exceeded' when authorize() or logoff() was called ?

### ISSUE THREAD

**Issue by Boriszn** [damienbod/angular-auth-oidc-client#197]
Hey 

Could you please help/suggest way to fix or mitigate this issue ?
 
I'm receiving error 'RangeError: Maximum call stack size exceeded' when calling `oidcSecurityService.authorize();` or `this.oidcSecurityService.logoff();` withing component. 

Detail error message stack:
```
RangeError: Maximum call stack size exceeded
NavbarComponent.html:14
message:"Maximum call stack size exceeded"
ngDebugContext:DebugContext_ {view: Object, nodeIndex: 2, nodeDef: Object, …}
ngErrorLogger:function () { … }
stack:"RangeError: Maximum call stack size exceeded\n    at Object.parse (<anonymous>)\n    at BrowserStorage.webpackJsonp.../../../../angular-auth-oidc-client/modules/angular-auth-oidc-client.es5.js.BrowserStorage.read (http://localhost:4200/vendor.bundle.js:14466:25)\n    at OidcSecurityCommon.webpackJsonp.../../../../angular-auth-oidc-client/modules/angular-auth-oidc-client.es5.js.OidcSecurityCommon.retrieve (http://localhost:4200/vendor.bundle.js:14521:41)\n    at OidcSecurityService.webpackJsonp.../../../../angular-auth-oidc-client/modules/angular-auth-oidc-client.es5.js.OidcSecurityService.authorize (http://localhost:4200/vendor.bundle.js:15416:61)\n    at SafeSubscriber._next (http://localhost:4200/main.bundle.js:894:43)\n    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.bundle.js:39334:16)\n    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next (http://localhost:4200/vendor.bundle.js:39281:22)\n    at Subscriber...
__proto__:Error {constructor: , name: "RangeError", message: "", …}
ERROR CONTEXT
```

**Comment by Boriszn** [comment]
Ok find-out the problem:
- Used old version of component (1.x.x)
- Also Http interceptor should be used with injector: Injector.

Thanks, ;)
