### ISSUE TITLE
Edge TypeError: Failed to fetch at _.sent

### ISSUE THREAD

**Issue by xaviergxf** [damienbod/angular-auth-oidc-client#267]
Hi @damienbod,

  I'm having the same error as #161. Here's all the log that i got:
```
 OidcConfigService 'load_using_stsServer' threw an error on calling https://userserver.com TypeError: Failed to fetch


vendor.js (72316,25)

[object Error]: {description: "Failed to fetch", message: "Failed to fetch", number: -2147418113, stack: "TypeError: Failed to fetch at _.sent (https://localhost:64385/vendor.js:72197:58) at Anonymous function (https://localhost:64385/vendor.js:72304:25) at step (https://localhost:64385/vendor.js:72218:13) at Anonymous function (https://localhost:64385/vendor.js:72199:46) at rejected (https://localhost:64385/vendor.js:72239:13) at ZoneDelegate.prototype.invoke (https://localhost:64385/polyfills.js:8000:13) at onInvoke (https://localhost:64385/vendor.js:42567:17) at ZoneDelegate.prototype.invoke (https://localhost:64385/polyfills.js:8000:13) at Zone.prototype.run (https://localhost:64385/polyfills.js:7752:17) at Anonymous function (https://localhost:64385/polyfills.js:8486:17)"}
description: "Failed to fetch"
message: "Failed to fetch"
number: -2147418113
stack: "TypeError: Failed to fetch at _.sent (https://localhost:64385/vendor.js:72197:58) at Anonymous function (https://localhost:64385/vendor.js:72304:25) at step (https://localhost:64385/vendor.js:72218:13) at Anonymous function (https://localhost:64385/vendor.js:72199:46) at rejected (https://localhost:64385/vendor.js:72239:13) at ZoneDelegate.prototype.invoke (https://localhost:64385/polyfills.js:8000:13) at onInvoke (https://localhost:64385/vendor.js:42567:17) at ZoneDelegate.prototype.invoke (https://localhost:64385/polyfills.js:8000:13) at Zone.prototype.run (https://localhost:64385/polyfills.js:7752:17) at Anonymous function (https://localhost:64385/polyfills.js:8486:17)"

```

I'm using version 6.0.5.

Thanks

**Comment by damienbod** [comment]
Are you using edge, or IE?

Add the fetch packages to the project, and the ie-shim

**Comment by damienbod** [comment]
https://github.com/damienbod/angular-auth-oidc-client/issues/242

**Comment by xaviergxf** [comment]
I tried the solutions proposed by you. I currently have isomorphic polyfill on my polyfills.ts. I even tried to add window['__Zone_disable_IE_check'] = true; on index.html without any success.

**Comment by damienbod** [comment]
The fetch has been removed in version 6.0.9

**Comment by sunilrav** [comment]
I still have this issue on 6.0.12.
