### ISSUE TITLE
Invalid Access Token 

### ISSUE THREAD

**Issue by leviplj** [damienbod/angular-auth-oidc-client#615]
I'm using Auth0.com as a Auth server and after logging in successfully the token returned is invalid such as "_AQPE0qiDhxLZny9OS5YifhHPDKiJMudH_".
I've mande a [StackBlitz App](https://stackblitz.com/edit/auth-oidc-test-phjp7t) that shows the problem. Only need to change the **stsServer** and the **client_id** on `assets/auth.clientConfiguration.json`

PS. I'm using auth code flow

**Comment by leviplj** [comment]
I figured out the problem is in the method `createAuthorizeUrl`. If the url doesn't contain the `audience` the `access_token` returned for the generated code is opaque and is not a JWT.

**Comment by leviplj** [comment]
I've downloaded the lib, build it with `npm run build-lib` and tried to install using `npm install ../path/to/repo/dist/angular-auth-oidc-client`. However I get the error bellow when I run my angular project.
```main.ts:12 NullInjectorError: StaticInjectorError(AppModule)[OidcSecurityService -> ConfigurationProvider]: 
  StaticInjectorError(Platform: core)[OidcSecurityService -> ConfigurationProvider]: 
    NullInjectorError: No provider for ConfigurationProvider!
    at NullInjector.get (http://localhost:4200/vendor.js:103993:27)
    at resolveToken (http://localhost:4200/vendor.js:118911:24)
    at tryResolveToken (http://localhost:4200/vendor.js:118837:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:118687:20)
    at resolveToken (http://localhost:4200/vendor.js:118911:24)
    at tryResolveToken (http://localhost:4200/vendor.js:118837:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:118687:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:129874:29)
    at _createClass (http://localhost:4200/vendor.js:129942:29)
    at _createProviderInstance (http://localhost:4200/vendor.js:129907:26)```

If I install the lib from npm package I don't get the error.

Is there anything else I need to do to use the lib from my local repo, or it must be publised to npm?

I've made some changes to fix the problem of this issue and I'd like to test first before sending a PR.

**Comment by damienbod** [comment]
Hi @leviplj 

The audience is not an standard parameter for the OIDC request. You can add any custom parameters you want by using the customParams function. 

Greetings Damien
