### ISSUE TITLE
ERROR NullInjectorError: StaticInjectorError when buildOptimizer is true

### ISSUE THREAD

**Issue by sadiqkhoja** [damienbod/angular-auth-oidc-client#803]
**Describe the bug**
if `buildOptimizer: true` in angular.json then application throws following error on startup: 

```
ERROR NullInjectorError: StaticInjectorError(AppModule)[angular_auth_oidc_client_OidcSecurityService -> CallbackService]: 
  StaticInjectorError(Platform: core)[angular_auth_oidc_client_OidcSecurityService -> CallbackService]: 
    NullInjectorError: No provider for CallbackService!
    at NullInjector.get (http://localhost:4200/main.8ad24f536c52ea8a4887.js:6:237639)
    at http://localhost:4200/main.8ad24f536c52ea8a4887.js:6:275744
    at tryResolveToken (http://localhost:4200/main.8ad24f536c52ea8a4887.js:6:276424)
    at StaticInjector.get (http://localhost:4200/main.8ad24f536c52ea8a4887.js:6:276641)
    at http://localhost:4200/main.8ad24f536c52ea8a4887.js:6:275744
    at tryResolveToken (http://localhost:4200/main.8ad24f536c52ea8a4887.js:6:276424)
    at StaticInjector.get (http://localhost:4200/main.8ad24f536c52ea8a4887.js:6:276641)
    at resolveNgModuleDep (http://localhost:4200/main.8ad24f536c52ea8a4887.js:6:315534)
    at http://localhost:4200/main.8ad24f536c52ea8a4887.js:6:316198
    at _createProviderInstance (http://localhost:4200/main.8ad24f536c52ea8a4887.js:6:316266)
```

**To Reproduce**
Build angular application with production configuration where buildOptimizer is true by default

**Expected behavior**
Angular app should start as it does with no buildOptimizer

**Screenshots**
![image](https://user-images.githubusercontent.com/447837/85960095-ddfb5a80-b96e-11ea-90f4-a9ef41c6a174.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 83.0.4103.116
 - angular-auth-oidc-client: ^11.0.0
- Angular: 8.2.0

**Comment by abdunnahid** [comment]
Facing the same issue

**Comment by damienbod** [comment]
@FabianGosebrink Any ideas here?

**Comment by FabianGosebrink** [comment]
This error should be gone with the latest versions.
