### ISSUE TITLE
IE 11 Silent Refresh 'silent renew failed! periodically check failed'

### ISSUE THREAD

**Issue by mluker** [damienbod/angular-auth-oidc-client#886]
IE11 fails when it attempts to silent renew. It works fine in other browsers. 

I have tried a few different silent-renew scripts, currently it looks like this.

```
<script>
    window.onload = function () {
        /* The parent window hosts the Angular application */
        var parent = window.parent;
        var isIE11 = !!window.MSInputMethodContext && !!document.documentMode
        var event;

        if (isIE11) {
            event = document.createEvent('CustomEvent');
            event.initCustomEvent('oidc-silent-renew-message', false, false, window.location);
        } else {
            /* Send the id_token information to the oidc message handler */
            event = new CustomEvent('oidc-silent-renew-message', { detail: window.location.hash.substr(1) });
        };
         parent.dispatchEvent(event);
    };
</script>
```

Console output shows
```
Checking: silentRenewRunning: false id_token: true userData: true
Has id_token expired: false, 1604085751000 > 1604085750850
Has access_token expired: false, 1604085778197 > 1604085750851
silent renew finished!
Checking: silentRenewRunning: false id_token: true userData: true
Has id_token expired: true, 1604085751000 > 1604085753830
Has access_token expired: false, 1604085778197 > 1604085753831
starting silent renew...
BEGIN refresh session Authorize Iframe renew
RefreshSession created. adding myautostate:  bce0ad6a1efae44661427a17d9efe46b1dCSQdNcP
   "RefreshSession created. adding myautostate: "
   [
      0: "bce0ad6a1efae44661427a17d9efe46b1dCSQdNcP",
      length: 1
   ]

silent renew failed! periodically check failed
   "silent renew failed!"
   [
      0: "periodically check failed",
      length: 1
   ]
```
I added some console logs to the silent-renew.html script and they are not showing up so I don't think its getting called.

**:: UPDATE ::**
I added a polyfill for CustomEvent and that got me farther. Its now calling the silent-renew.html but then getting a JS error.

```
npm install --save custom-event-polyfill
then include/require it in your javascript
import 'custom-event-polyfill';
```

Now the error is
```
Checking: silentRenewRunning: false id_token: true userData: true
Has id_token expired: false, 1604100346000 > 1604100204833
Has access_token expired: false, 1604100351236 > 1604100204834
silent renew finished!
Checking: silentRenewRunning: false id_token: true userData: true
Has id_token expired: false, 1604100346000 > 1604100208264
Has access_token expired: false, 1604100351236 > 1604100208264
silent renew finished!
Checking: silentRenewRunning: false id_token: true userData: true
Has id_token expired: true, 1604100346000 > 1604100347702
Has access_token expired: false, 1604100351236 > 1604100347702
starting silent renew...
BEGIN refresh session Authorize Iframe renew
RefreshSession created. adding myautostate:  46c2ac8a2c7f37942008ffa6647a342e97iL0Sdty
   "RefreshSession created. adding myautostate: "
   [
      0: "46c2ac8a2c7f37942008ffa6647a342e97iL0Sdty",
      length: 1
   ]

sendAuthorizeReqestUsingSilentRenew for URL: redacted
Checking: silentRenewRunning: true id_token: true userData: true
silent renew finished!
silentRenewEventHandler
BEGIN authorizedCallback, no auth data
ERROR TypeError: Object doesn't support property or method 'split'
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'split'",
      message: "Object doesn't support property or method 'split'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'split'
   at e.prototype.implicitFlowCallback (http://localhost:4200/main.11b29d8b59529fae2ed7.js:1:3363299)
   at e.prototype.processImplicitFlowCallback (http://localhost:4200/main.11b29d8b59529fae2ed7.js:1:3361900)
   at e.prototype.authorizedImplicitFlowCallback (http://localhost:4200/main.11b29d8b59529fae2ed7.js:1:3375357)
   at e.prototype.silentRenewEventHandler (http://localhost:4200/main.11b29d8b59529fae2ed7.js:1:3378124)
   at Anonymous function (http://localhost:4200/main.11b29d8b59529fae2ed7.js:1:3386254)
   at Anonymous function (http://localhost:4200/main.11b29d8b59529fae2ed7.js:1:3014740)
   at t.prototype.invokeTask (http://localhost:4200/polyfills-es5.510fbd2c372a90e6f921.js:1:9914)
   at onInvokeTask (http://localhost:4200/main.11b29d8b59529fae2ed7.js:1:577388)
   at t.prototype.invokeTask (http://localhost:4200/polyfills-es5.510fbd2c372a90e6f921.js:1:9914)
   at e.prototype.runTask (http://localhost:4200/polyfills-es5.510fbd2c372a90e6f92",
      Symbol()_9.g5rn87zru1b: undefined,
      Symbol(INITIAL_VALUE)_k.g5rn87zru1b: undefined,
      Symbol(rxSubscriber)_j.g5rn87zru1b: undefined
   }

removed event listener from IFrame
Checking: silentRenewRunning: true id_token: true userData: true
silent renew finished!
Checking: silentRenewRunning: true id_token: true userData: true
silent renew finished!
```

As you can see, its no longer checking the expiration after the JS error so it never renews.

Error is happening in 
```

  // STEP 1 Implicit Flow
    FlowsService.prototype.implicitFlowCallback = function (hash) { .......
```

![image](https://user-images.githubusercontent.com/2166010/97765894-127c5000-1ae2-11eb-8aed-912c059a4217.png)

**Comment by mluker** [comment]
I was able to figure it out. Looks like I was missing a polyfill for custom events.

npm install --save custom-event-polyfill

then include/require it in your javascript via import 'custom-event-polyfill';

**Comment by mluker** [comment]
For everyone playing along at home. I found the solution to get IE11 to work with silent-renew.

Install this polyfill
```
npm install --save custom-event-polyfill
```

Then include/require the following in your javascript
```
import 'core-js/es/array';
import 'core-js/es/object';
import 'custom-event-polyfill';
```

Then update your silent-renew
```
<script>
    window.onload = function () {
        /* The parent window hosts the Angular application */
        var parent = window.parent;
        var isIE11 = !!window.MSInputMethodContext && !!document.documentMode
        var event;

        if (isIE11) {
            event = document.createEvent('CustomEvent');
            event.initCustomEvent('oidc-silent-renew-message', false, false, window.location.hash.substr(1));
        } else {
            /* Send the id_token information to the oidc message handler */
            event = new CustomEvent('oidc-silent-renew-message', { detail: window.location.hash.substr(1) });
        };
        parent.dispatchEvent(event);
    };
</script>
```
